# Generated by Django 5.2.6 on 2025-09-26 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original', models.CharField(max_length=100, verbose_name='Иностранное слово')),
                ('translation', models.CharField(max_length=100, verbose_name='Перевод')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('knowledge_level', models.IntegerField(default=0, verbose_name='Уровень знания')),
                ('next_review', models.DateTimeField(blank=True, null=True, verbose_name='Следующее повторение')),
            ],
            options={
                'verbose_name': 'Слово',
                'verbose_name_plural': 'Слова',
                'ordering': ['-date_added'],
            },
        ),
    ]
