# Generated by Django 5.2.6 on 2025-09-26 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_vocab', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='transcription',
            field=models.CharField(blank=True, max_length=100, verbose_name='Транскрипция'),
        ),
    ]
