# Generated by Django 5.2.6 on 2025-09-29 16:41

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_vocab', '0002_word_transcription'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='word',
            name='knowledge_level',
        ),
        migrations.RemoveField(
            model_name='word',
            name='next_review',
        ),
        migrations.AddField(
            model_name='word',
            name='difficulty_level',
            field=models.IntegerField(choices=[(1, 'Легкий'), (2, 'Средний'), (3, 'Сложный')], default=2, verbose_name='Уровень сложности'),
        ),
        migrations.AddField(
            model_name='word',
            name='example_sentence',
            field=models.TextField(blank=True, verbose_name='Пример использования'),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField(blank=True, null=True, verbose_name='Telegram ID')),
                ('daily_review_limit', models.IntegerField(default=20, verbose_name='Лимит повторений в день')),
                ('notification_enabled', models.BooleanField(default=True, verbose_name='Уведомления включены')),
                ('total_words_learned', models.IntegerField(default=0, verbose_name='Всего изучено слов')),
                ('total_reviews', models.IntegerField(default=0, verbose_name='Всего повторений')),
                ('streak_days', models.IntegerField(default=0, verbose_name='Дней подряд')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Профиль пользователя',
                'verbose_name_plural': 'Профили пользователей',
            },
        ),
        migrations.CreateModel(
            name='UserWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interval', models.IntegerField(default=0, verbose_name='Интервал (дни)')),
                ('repetition', models.IntegerField(default=0, verbose_name='Номер повторения')),
                ('ease_factor', models.FloatField(default=2.5, verbose_name='Фактор легкости')),
                ('next_review', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Следующее повторение')),
                ('correct_answers', models.IntegerField(default=0, verbose_name='Правильных ответов')),
                ('wrong_answers', models.IntegerField(default=0, verbose_name='Неправильных ответов')),
                ('last_reviewed', models.DateTimeField(blank=True, null=True, verbose_name='Последнее повторение')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления пользователю')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_vocab.word', verbose_name='Слово')),
            ],
            options={
                'verbose_name': 'Прогресс пользователя',
                'verbose_name_plural': 'Прогресс пользователей',
                'unique_together': {('user', 'word')},
            },
        ),
    ]
