# Generated by Django 5.2.6 on 2025-09-30 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_vocab', '0003_remove_word_knowledge_level_remove_word_next_review_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='daily_goal_reminder',
            field=models.BooleanField(default=True, verbose_name='Напоминание о целях'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='daily_new_words',
            field=models.IntegerField(default=5, verbose_name='Новых слов в день'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='default_interval',
            field=models.IntegerField(default=1, verbose_name='Базовый интервал (дни)'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='enable_matching',
            field=models.BooleanField(default=True, verbose_name='Сопоставление'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='enable_multiple_choice',
            field=models.BooleanField(default=True, verbose_name='Тест с выбором'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='test_questions_count',
            field=models.IntegerField(default=10, verbose_name='Вопросов в тесте'),
        ),
    ]
